markdownlint:
  default: true

  MD007:
    indent: 2

  MD013:
    line_length: 120
    tables: false
    stern: true

  MD024:
    siblings_only: true

  MD029:
    style: ordered

  MD033:
    allowed_elements:
      - details
      - summary

rubocop:
  require:
    - rubocop-performance
    - rubocop-rspec

  AllCops:
    Exclude:
      - vendor/**/*
    NewCops: enable

  Layout/LeadingCommentSpace:
    AllowRBSInlineAnnotation: true

  Metrics/MethodLength:
    CountAsOne:
      - array
      - hash
      - heredoc
      - method_call

  Naming/FileName:
    Exclude:
      - '**/rubocop-*'

  RSpec/ExampleLength:
    Max: 15

  RSpec/MultipleMemoizedHelpers:
    Max: 10

  RSpec/NestedGroups:
    AllowedGroups:
      - describe

  Style/Documentation:
    AllowedConstants:
      - Domainic
