require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Naming/FileName:
  Exclude:
    - '**/domainic-*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  AllowedGroups:
    - describe

Style/Documentation:
  AllowedConstants:
    - Domainic
